import { useState, useEffect, useRef, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { MessageSquare, X, Send, Bot, User, Minimize2, Maximize2, Sparkles, BrainCircuit, ChevronRight, Info, Brain } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { MOCK_FACULTY } from "@/data/mockFaculty";
import { MOCK_COURSES } from "@/data/mockCourses";
import { MOCK_STUDENTS } from "@/data/mockStudents";

export function SmartAssistant() {
    const [isOpen, setIsOpen] = useState(false);
    const [isMinimized, setIsMinimized] = useState(false);
    const [input, setInput] = useState("");
    const [messages, setMessages] = useState([
        { role: 'bot', content: "Hello! I'm the SmartCampus360 AI. How can I help you today? You can ask about your timetable, exam seating, or faculty details." }
    ]);
    const [isTyping, setIsTyping] = useState(false);
    const scrollRef = useRef<HTMLDivElement>(null);

    // Context Data
    const currentUser = useMemo(() => {
        const saved = localStorage.getItem('smartcampus_user');
        return saved ? JSON.parse(saved) : null;
    }, []);

    useEffect(() => {
        if (scrollRef.current) {
            scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
        }
    }, [messages, isTyping]);

    const getResponse = (query: string) => {
        const q = query.toLowerCase();
        
        // 1. Timetable Queries
        if (q.includes('timetable') || q.includes('schedule')) {
            return "Based on the current institutional timetable, your next session is at 11:40 AM. You can view your full weekly schedule in the 'Timetable' section of your dashboard.";
        }
        
        // 2. Exam Seating Queries
        if (q.includes('exam') || q.includes('seat') || q.includes('room')) {
            const seatingStr = localStorage.getItem('EXAM_SEATING_PLAN');
            if (seatingStr && currentUser) {
                const seating = JSON.parse(seatingStr);
                const plan = seating.find((s: any) => s.rollNumber.toUpperCase() === currentUser.id.toUpperCase());
                if (plan) {
                    return `I found your allocation! For your upcoming exam, you are seated in ${plan.room} (${plan.block}), Seat ${plan.seatNumber}.`;
                }
            }
            return "Exam seating plans are generated by the admin. Please check back later or visit the 'Exams' module for official notification.";
        }
        
        // 3. Faculty Queries
        if (q.includes('faculty') || q.includes('teacher') || q.includes('who is')) {
            const facultyName = MOCK_FACULTY.find(f => q.includes(f.name.toLowerCase()));
            if (facultyName) {
                return `${facultyName.name} is a faculty in the ${facultyName.department} department. Their designation is ${facultyName.designation}. For office hours, please visit their department floor.`;
            }
            return "I can help you find faculty details. Try asking 'Who is [Faculty Name]?' or 'Tell me about the CSE faculty'.";
        }

        // 4. Subject/Course Queries
        if (q.includes('course') || q.includes('subject') || q.includes('credit')) {
            return "The current semester features 6 core subjects and 2 laboratory sessions. Each core subject carries 3-4 academic credits. You can find the syllabus in 'My Courses'.";
        }

        // 5. General Rules / Navigation
        if (q.includes('attendance') || q.includes('percentage')) {
            return "Institutional policy requires a minimum of 75% attendance to be eligible for semester examinations. You can track your real-time buffer in your dashboard.";
        }

        return "I'm still learning about that. Try asking about your timetable, seat allocation, or faculty details!";
    };

    const handleSend = async (customQuery?: string) => {
        const queryText = customQuery || input;
        if (!queryText.trim()) return;
        
        setMessages(prev => [...prev, { role: 'user', content: queryText }]);
        setInput("");
        setIsTyping(true);

        setTimeout(() => {
            const botResponse = getResponse(queryText);
            setMessages(prev => [...prev, { role: 'bot', content: botResponse }]);
            setIsTyping(false);
        }, 1000);
    };

    const suggestions = [
        "Where is my exam seat?",
        "Who is Dr. Rajesh?",
        "My tomorrow's timetable",
        "Attendance Policy"
    ];

    return (
        <div className="fixed bottom-6 right-6 z-[100] flex flex-col items-end">
            <AnimatePresence>
                {isOpen && (
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9, y: 20 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.9, y: 20 }}
                        className={`mb-4 w-[380px] sm:w-[420px] shadow-[0_20px_50px_rgba(0,0,0,0.25)] rounded-[2.5rem] overflow-hidden border border-border/50 transition-all duration-300 ${isMinimized ? 'h-20' : 'h-[600px]'}`}
                    >
                        <Card className="h-full flex flex-col border-none rounded-none bg-background/90 backdrop-blur-3xl">
                            <CardHeader className="bg-primary p-6 flex flex-row items-center justify-between space-y-0 shrink-0">
                                <div className="flex items-center gap-4">
                                    <div className="h-12 w-12 rounded-2xl bg-white/20 flex items-center justify-center backdrop-blur-md border border-white/10">
                                        <Bot className="h-7 w-7 text-white" />
                                    </div>
                                    <div className="text-left">
                                        <CardTitle className="text-white text-base font-black uppercase tracking-widest leading-none">Campus AI</CardTitle>
                                    </div>
                                </div>
                                <div className="flex items-center gap-2">
                                    <Button size="icon" variant="ghost" className="h-9 w-9 text-white/50 hover:text-white hover:bg-white/10 rounded-xl" onClick={() => setIsMinimized(!isMinimized)}>
                                        {isMinimized ? <Maximize2 className="h-4 w-4" /> : <Minimize2 className="h-4 w-4" />}
                                    </Button>
                                    <Button size="icon" variant="ghost" className="h-9 w-9 text-white/50 hover:text-white hover:bg-white/10 rounded-xl" onClick={() => setIsOpen(false)}>
                                        <X className="h-4 w-4" />
                                    </Button>
                                </div>
                            </CardHeader>
                            
                            {!isMinimized && (
                                <>
                                    <CardContent className="flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar" ref={scrollRef}>
                                        {messages.map((msg, i) => (
                                            <motion.div
                                                key={i}
                                                initial={{ opacity: 0, scale: 0.95, y: 10 }}
                                                animate={{ opacity: 1, scale: 1, y: 0 }}
                                                className={`flex ${msg.role === 'bot' ? 'justify-start' : 'justify-end'}`}
                                            >
                                                <div className={`flex gap-3 max-w-[85%] ${msg.role === 'user' && 'flex-row-reverse'}`}>
                                                    <div className={`h-8 w-8 rounded-full flex items-center justify-center shrink-0 border ${
                                                        msg.role === 'bot' ? 'bg-muted border-border' : 'bg-primary border-primary shadow-lg shadow-primary/20'
                                                    }`}>
                                                        {msg.role === 'bot' ? <Bot className="h-4 w-4" /> : <User className="h-4 w-4 text-white" />}
                                                    </div>
                                                    <div className={`rounded-3xl p-4 text-sm font-medium shadow-sm leading-relaxed ${
                                                        msg.role === 'bot' 
                                                            ? 'bg-muted/50 text-foreground rounded-tl-none border border-border/50' 
                                                            : 'bg-primary text-primary-foreground rounded-tr-none'
                                                    }`}>
                                                        {msg.content}
                                                    </div>
                                                </div>
                                            </motion.div>
                                        ))}
                                        {isTyping && (
                                            <div className="flex justify-start">
                                                <div className="bg-muted/50 rounded-2xl rounded-tl-none px-4 py-3 space-x-1.5 flex items-center border border-border/30">
                                                    <div className="w-1.5 h-1.5 bg-primary/40 rounded-full animate-bounce" />
                                                    <div className="w-1.5 h-1.5 bg-primary/40 rounded-full animate-bounce [animation-delay:0.2s]" />
                                                    <div className="w-1.5 h-1.5 bg-primary/40 rounded-full animate-bounce [animation-delay:0.4s]" />
                                                </div>
                                            </div>
                                        )}
                                        
                                        {/* Suggestions Grid */}
                                        <div className="grid grid-cols-2 gap-2 pt-4">
                                            {suggestions.map((s, idx) => (
                                                <Button 
                                                    key={idx} 
                                                    variant="outline" 
                                                    className="h-auto py-2.5 px-3 rounded-2xl text-[10px] font-bold text-left justify-start uppercase tracking-widest border-border/50 hover:bg-primary/5 hover:text-primary transition-all group overflow-hidden"
                                                    onClick={() => handleSend(s)}
                                                >
                                                    <span className="truncate flex-1">{s}</span>
                                                    <ChevronRight className="h-3 w-3 ml-1 opacity-0 group-hover:opacity-100 transition-opacity" />
                                                </Button>
                                            ))}
                                        </div>
                                    </CardContent>
                                    
                                    <div className="p-6 bg-muted/20 border-t border-border/50 shrink-0">
                                        <div className="flex gap-3 relative">
                                            <Input
                                                placeholder="Message Campus AI..."
                                                value={input}
                                                onChange={(e) => setInput(e.target.value)}
                                                onKeyPress={(e) => e.key === 'Enter' && handleSend()}
                                                className="rounded-2xl pr-14 h-14 bg-background/50 border-border/50 transition-all focus:ring-primary/20 font-medium"
                                            />
                                            <Button size="icon" className="absolute right-1.5 top-1.5 h-11 w-11 rounded-xl bg-primary hover:bg-primary/90 transition-transform hover:scale-105 shadow-lg shadow-primary/25" onClick={() => handleSend()}>
                                                <Send className="h-5 w-5" />
                                            </Button>
                                        </div>
                                    </div>
                                </>
                            )}
                        </Card>
                    </motion.div>
                )}
            </AnimatePresence>

            <motion.div
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
            >
                <Button
                    onClick={() => setIsOpen(!isOpen)}
                    className="h-16 w-16 rounded-full shadow-[0_10px_40px_rgba(0,0,0,0.2)] bg-primary hover:bg-primary/90 text-primary-foreground p-0 flex items-center justify-center transition-all"
                >
                    <AnimatePresence mode="wait">
                        {isOpen ? (
                            <motion.div key="close" initial={{ rotate: -90, opacity: 0 }} animate={{ rotate: 0, opacity: 1 }} exit={{ rotate: 90, opacity: 0 }}>
                                <Minimize2 className="h-6 w-6" />
                            </motion.div>
                        ) : (
                            <motion.div key="chat" initial={{ scale: 0, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0, opacity: 0 }} className="relative flex items-center justify-center">
                                <Brain className="h-9 w-9 drop-shadow-[0_0_10px_rgba(255,255,255,0.4)]" />
                            </motion.div>
                        )}
                    </AnimatePresence>
                </Button>
            </motion.div>
        </div>
    );
}
