// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkjiocpcdsznlbqgwbql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhramlvY3BjZHN6bmxicWd3YnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjM4NzIsImV4cCI6MjA2OTI5OTg3Mn0.wH80AkVSPVY6Ij8PTw20pJPAki3NN4KXH4DHnC_wIXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});